# Generated by Django 5.2.6 on 2025-09-15 02:25

from django.db import migrations
from phonenumbers import parse, is_valid_number, PhoneNumberFormat, format_number

def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            parsed_phone = parse(flat.owners_phonenumber, 'RU')
            if is_valid_number(parsed_phone):
                flat.owner_pure_phone = format_number(parsed_phone, PhoneNumberFormat.E164)
        except Exception:
            # В случае любой ошибки (например, неверный формат номера),
            # оставляем новое поле пустым
            flat.owner_pure_phone = None
        flat.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
    ]
