# Generated by Django 5.2.6 on 2025-09-15 03:09

from django.db import migrations
from phonenumbers import parse, is_valid_number, PhoneNumberFormat, format_number


def move_owners_to_new_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner_name = flat.owner
        owner_phonenumber = flat.owners_phonenumber
        
        # Нормализуем номер телефона
        owner_pure_phone = None
        try:
            parsed_phone = parse(owner_phonenumber, 'RU')
            if is_valid_number(parsed_phone):
                owner_pure_phone = format_number(parsed_phone, PhoneNumberFormat.E164)
        except Exception:
            pass

            
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners_to_new_model),
    ]
