# Generated by Django 5.2.6 on 2025-09-15 03:25

from django.db import migrations
from phonenumbers import parse, is_valid_number, PhoneNumberFormat, format_number

def update_owners_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    # Теперь мы будем итерироваться по Flat и обновлять Owner
    for flat in Flat.objects.all():
        owner_name = flat.owner
        owner_phonenumber = flat.owners_phonenumber
        
        owner_pure_phone = None
        try:
            parsed_phone = parse(owner_phonenumber, 'RU')
            if is_valid_number(parsed_phone):
                owner_pure_phone = format_number(parsed_phone, PhoneNumberFormat.E164)
        except Exception:
            pass

        # Используем .filter(), чтобы найти уже существующего собственника
        owners_to_update = Owner.objects.filter(owner_name=owner_name)
        
        for owner in owners_to_update:
            owner.phonenumber = owner_phonenumber
            owner.owner_pure_phone = owner_pure_phone
            owner.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),  # Зависимость от предыдущей миграции
    ]

    operations = [
        migrations.RunPython(update_owners_data),
    ]
