# Generated by Django 5.2.6 on 2025-09-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250915_1009'),
        ('property', '0012_auto_20250915_1025'),
    ]

    operations = [
    ]
